# Generated by Django 3.2.16 on 2022-11-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatusNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('bpm', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
                ('slope', models.IntegerField(null=True)),
                ('now', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.patient')),
            ],
            options={
                'db_table': 'patient_status_now',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientStatusExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('bpm', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
                ('slope', models.IntegerField(null=True)),
                ('now', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.patient')),
            ],
            options={
                'db_table': 'patient_status_excel',
                'managed': True,
            },
        ),
    ]
