# Generated by Django 3.2.16 on 2022-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='discharged_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospitalized_date',
            field=models.DateField(),
        ),
    ]
