# Generated by Django 3.2.16 on 2022-11-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_type',
            field=models.CharField(default='patient', max_length=7),
        ),
        migrations.AddField(
            model_name='ward',
            name='user_type',
            field=models.CharField(default='ward', max_length=4),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor/default.jpg', upload_to='doctor/'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='image',
            field=models.ImageField(default='nurse/default.jpg', upload_to='nurse/'),
        ),
    ]
