# Generated by Django 3.2.16 on 2022-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_patientstatusexcel_patientstatusnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStatusDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('bpm', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
            ],
            options={
                'db_table': 'patient_status_default',
                'managed': True,
            },
        ),
    ]
