# Generated by Django 3.2.16 on 2022-11-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_patientstatusdefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_t', models.FloatField()),
                ('max_t', models.FloatField()),
                ('min_b', models.IntegerField()),
                ('max_b', models.IntegerField()),
                ('min_o', models.IntegerField()),
                ('max_o', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.patient')),
            ],
            options={
                'db_table': 'patient_day',
                'managed': True,
            },
        ),
    ]
