# Generated by Django 3.2.16 on 2022-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_alter_patientstatus_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_warning',
            field=models.BooleanField(default=False),
        ),
    ]
