# Generated by Django 3.2.16 on 2022-11-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0004_patient_is_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstatus',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_status', to='wards.patient'),
        ),
    ]
