# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget,QGraphicsDropShadowEffect, QGraphicsOpacityEffect)

import myres_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1366, 768)
        Form.setStyleSheet(u"background-color: rgb(246, 247, 248);")
        self.logo_link = QLabel(Form)
        self.logo_link.setObjectName(u"logo_link")
        self.logo_link.setGeometry(QRect(609, 58, 148, 50))
        self.logo_link.setStyleSheet(u"border-image: url(:/logo/img/logo_little.png);")
        self.box5 = QLabel(Form)
        self.box5.setObjectName(u"box5")
        self.box5.setGeometry(QRect(551, 545, 264, 82))
        self.box5.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;\n"
"shadow: 0px 4px 10px rgba(184, 184, 184, 0.2);")
        self.box5.setFrameShape(QFrame.StyledPanel)
        self.box5.setFrameShadow(QFrame.Raised)
        self.box5.setLineWidth(10)
        self.pushButton_bms = QPushButton(Form)
        self.pushButton_bms.setObjectName(u"pushButton_bms")
        self.pushButton_bms.setGeometry(QRect(551, 545, 264, 82))
        self.pushButton_bms.setStyleSheet(u"background-color: rgba(255, 255, 255,0);")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(582, 565, 41, 41))
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-image: url(:/icons/img/capsule_icon.png);")
        self.label_text = QLabel(Form)
        self.label_text.setObjectName(u"label_text")
        self.label_text.setGeometry(QRect(648, 565, 131, 41))
        font = QFont()
        font.setFamilies([u"Noto Sans KR"])
        font.setPointSize(16)
        font.setBold(True)
        self.label_text.setFont(font)
        self.label_text.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(26, 50, 98);")
        self.balance_btn_off = QPushButton(Form)
        self.balance_btn_off.setObjectName(u"balance_btn_off")
        self.balance_btn_off.setEnabled(True)
        self.balance_btn_off.setGeometry(QRect(775, 398, 122, 42))
        self.balance_btn_off.setStyleSheet(u"border-radius : 50%;\n"
"border-image: url(:/icons/img/toggle_off.png);")
        self.balance_btn_off.setIconSize(QSize(122, 42))
        self.balance_btn_off.setCheckable(False)
        self.balance_btn_off.setChecked(False)
        self.balance_btn_off.setAutoRepeat(False)
        self.balance_btn_off.setFlat(True)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(454, 390, 250, 57))
        font1 = QFont()
        font1.setFamilies([u"Noto Sans KR"])
        font1.setPointSize(28)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color : rgb(255,255,255);")
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(454, 214, 251, 130))
        self.label_3.setStyleSheet(u"border-image: url(:/icons/img/battery.png);\n"
"background-color : rgb(255,255,255);")
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(874, 246, 51, 61))
        font2 = QFont()
        font2.setPointSize(40)
        font2.setBold(True)
        self.label_4.setFont(font2)
        self.label_4.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color : rgb(255,255,255);")
        self.battery_amount = QLabel(Form)
        self.battery_amount.setObjectName(u"battery_amount")
        self.battery_amount.setGeometry(QRect(774, 236, 91, 81))
        font3 = QFont()
        font3.setFamilies([u"Noto Sans KR"])
        font3.setPointSize(40)
        font3.setBold(True)
        self.battery_amount.setFont(font3)
        self.battery_amount.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color : rgb(255,255,255);")
        self.battery_amount_bar = QLabel(Form)
        self.battery_amount_bar.setObjectName(u"battery_amount_bar")
        self.battery_amount_bar.setGeometry(QRect(472, 233, 200, 93))
        self.battery_amount_bar.setStyleSheet(u"background-color: rgb(26, 50, 98);")
        self.box2 = QLabel(Form)
        self.box2.setObjectName(u"box2")
        self.box2.setGeometry(QRect(1020, 138, 244, 170))
        self.box2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1060, 164, 40, 40))
        self.label_6.setStyleSheet(u"border-image: url(:/icons/img/temp_icon_little.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(1113, 171, 47, 27))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.temp_label = QLabel(Form)
        self.temp_label.setObjectName(u"temp_label")
        self.temp_label.setGeometry(QRect(1092, 229, 100, 44))
        font4 = QFont()
        font4.setFamilies([u"Noto Sans KR"])
        font4.setPointSize(26)
        font4.setBold(True)
        self.temp_label.setFont(font4)
        self.temp_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.temp_label.setAlignment(Qt.AlignCenter)
        self.box3 = QLabel(Form)
        self.box3.setObjectName(u"box3")
        self.box3.setGeometry(QRect(1020, 330, 244, 170))
        self.box3.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.box4 = QLabel(Form)
        self.box4.setObjectName(u"box4")
        self.box4.setGeometry(QRect(1020, 522, 244, 170))
        self.box4.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1060, 356, 40, 40))
        self.label_11.setStyleSheet(u"border-image: url(:/icons/img/heart_icon.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1060, 548, 40, 40))
        self.label_12.setStyleSheet(u"border-image: url(:/icons/img/oxygen-icon.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(1108, 363, 80, 27))
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(1108, 555, 134, 27))
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.heart_label = QLabel(Form)
        self.heart_label.setObjectName(u"heart_label")
        self.heart_label.setGeometry(QRect(1092, 412, 100, 44))
        self.heart_label.setFont(font4)
        self.heart_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.heart_label.setAlignment(Qt.AlignCenter)
        self.o2_label = QLabel(Form)
        self.o2_label.setObjectName(u"o2_label")
        self.o2_label.setGeometry(QRect(1092, 613, 100, 44))
        self.o2_label.setFont(font4)
        self.o2_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.o2_label.setAlignment(Qt.AlignCenter)
        self.box1 = QLabel(Form)
        self.box1.setObjectName(u"box1")
        self.box1.setGeometry(QRect(66, 138, 280, 554))
        self.box1.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(112, 160, 188, 35))
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(26, 50, 98);")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(96, 252, 80, 20))
        font5 = QFont()
        font5.setFamilies([u"Noto Sans KR"])
        font5.setPointSize(14)
        font5.setBold(False)
        self.label_16.setFont(font5)
        self.label_16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(96, 310, 80, 20))
        self.label_17.setFont(font5)
        self.label_17.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(96, 368, 80, 20))
        self.label_18.setFont(font5)
        self.label_18.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(96, 426, 80, 20))
        self.label_19.setFont(font5)
        self.label_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(96, 484, 80, 20))
        self.label_20.setFont(font5)
        self.label_20.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.seperate_bar = QLabel(Form)
        self.seperate_bar.setObjectName(u"seperate_bar")
        self.seperate_bar.setGeometry(QRect(190, 252, 2, 21))
        self.seperate_bar.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_2 = QLabel(Form)
        self.seperate_bar_2.setObjectName(u"seperate_bar_2")
        self.seperate_bar_2.setGeometry(QRect(190, 310, 2, 21))
        self.seperate_bar_2.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_3 = QLabel(Form)
        self.seperate_bar_3.setObjectName(u"seperate_bar_3")
        self.seperate_bar_3.setGeometry(QRect(190, 368, 2, 21))
        self.seperate_bar_3.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_4 = QLabel(Form)
        self.seperate_bar_4.setObjectName(u"seperate_bar_4")
        self.seperate_bar_4.setGeometry(QRect(190, 426, 2, 21))
        self.seperate_bar_4.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_5 = QLabel(Form)
        self.seperate_bar_5.setObjectName(u"seperate_bar_5")
        self.seperate_bar_5.setGeometry(QRect(190, 484, 2, 21))
        self.seperate_bar_5.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.p_num = QLabel(Form)
        self.p_num.setObjectName(u"p_num")
        self.p_num.setGeometry(QRect(210, 252, 91, 20))
        font6 = QFont()
        font6.setFamilies([u"Noto Sans KR"])
        font6.setPointSize(14)
        font6.setBold(True)
        self.p_num.setFont(font6)
        self.p_num.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_name = QLabel(Form)
        self.p_name.setObjectName(u"p_name")
        self.p_name.setGeometry(QRect(210, 310, 91, 20))
        self.p_name.setFont(font6)
        self.p_name.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_age = QLabel(Form)
        self.p_age.setObjectName(u"p_age")
        self.p_age.setGeometry(QRect(210, 368, 91, 20))
        self.p_age.setFont(font6)
        self.p_age.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gender = QLabel(Form)
        self.p_gender.setObjectName(u"p_gender")
        self.p_gender.setGeometry(QRect(210, 426, 91, 20))
        self.p_gender.setFont(font6)
        self.p_gender.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard = QLabel(Form)
        self.p_gard.setObjectName(u"p_gard")
        self.p_gard.setGeometry(QRect(210, 484, 91, 20))
        self.p_gard.setFont(font6)
        self.p_gard.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_21 = QLabel(Form)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(96, 600, 141, 20))
        self.label_21.setFont(font5)
        self.label_21.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard_2 = QLabel(Form)
        self.p_gard_2.setObjectName(u"p_gard_2")
        self.p_gard_2.setGeometry(QRect(115, 630, 180, 31))
        font7 = QFont()
        font7.setFamilies([u"Noto Sans KR"])
        font7.setPointSize(15)
        font7.setBold(True)
        self.p_gard_2.setFont(font7)
        self.p_gard_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard_2.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(Form)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(96, 542, 61, 20))
        self.label_22.setFont(font5)
        self.label_22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(210, 542, 81, 31))
        self.label_23.setFont(font6)
        self.label_23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.balance_btn_on = QPushButton(Form)
        self.balance_btn_on.setObjectName(u"balance_btn_on")
        self.balance_btn_on.setGeometry(QRect(775, 398, 122, 42))
        self.balance_btn_on.setStyleSheet(u"border-radius : 50%;\n"
"border-image: url(:/icons/img/toggle_on.png);")
        self.balance_btn_on.setIconSize(QSize(122, 42))
        self.balance_btn_on.setCheckable(False)
        self.balance_btn_on.setChecked(False)
        self.balance_btn_on.setAutoRepeat(False)
        self.balance_btn_on.setFlat(True)
        self.seperate_bar_6 = QLabel(Form)
        self.seperate_bar_6.setObjectName(u"seperate_bar_6")
        self.seperate_bar_6.setGeometry(QRect(190, 542, 2, 21))
        self.seperate_bar_6.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.box6 = QLabel(Form)
        self.box6.setObjectName(u"box6")
        self.box6.setGeometry(QRect(387, 138, 590, 377))
        self.box6.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(780, 460, 161, 20))
        font8 = QFont()
        font8.setFamilies([u"Noto Sans KR"])
        font8.setPointSize(12)
        self.label_5.setFont(font8)
        self.label_5.setStyleSheet(u"background-color : rgb(255,,255,255);\n"
"color: rgb(234, 84, 85);")
        self.exit_btn = QPushButton(Form)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(1227, 58, 36, 44))
        self.exit_btn.setStyleSheet(u"border-image: url(:/icons/img/exit_icon.png);")

        self.shadow1 = QGraphicsDropShadowEffect()
        self.shadow1.setColor(QColor(212, 212, 212))
        self.shadow1.setBlurRadius(15)
        self.shadow1.setOffset(4)

        self.shadow2 = QGraphicsDropShadowEffect()
        self.shadow2.setColor(QColor(212, 212, 212))
        self.shadow2.setBlurRadius(15)
        self.shadow2.setOffset(4)

        self.shadow3 = QGraphicsDropShadowEffect()
        self.shadow3.setColor(QColor(212, 212, 212))
        self.shadow3.setBlurRadius(15)
        self.shadow3.setOffset(4)

        self.shadow4 = QGraphicsDropShadowEffect()
        self.shadow4.setColor(QColor(212, 212, 212))
        self.shadow4.setBlurRadius(15)
        self.shadow4.setOffset(4)

        self.shadow5 = QGraphicsDropShadowEffect()
        self.shadow5.setColor(QColor(212, 212, 212))
        self.shadow5.setBlurRadius(15)
        self.shadow5.setOffset(4)

        self.shadow6 = QGraphicsDropShadowEffect()
        self.shadow6.setColor(QColor(212, 212, 212))
        self.shadow6.setBlurRadius(15)
        self.shadow6.setOffset(4)

        self.box1.setGraphicsEffect(self.shadow1)
        self.box2.setGraphicsEffect(self.shadow2)
        self.box3.setGraphicsEffect(self.shadow3)
        self.box4.setGraphicsEffect(self.shadow4)
        self.box5.setGraphicsEffect(self.shadow5)
        self.box6.setGraphicsEffect(self.shadow6)

        opacity_effect = QGraphicsOpacityEffect(self.pushButton_bms)
        opacity_effect.setOpacity(0)
        self.pushButton_bms.setGraphicsEffect(opacity_effect)

        self.box6.raise_()
        self.logo_link.raise_()
        self.box5.raise_()
        self.label.raise_()
        self.label_text.raise_()
        self.balance_btn_off.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_bms.raise_()
        self.battery_amount_bar.raise_()
        self.box2.raise_()
        self.label_7.raise_()
        self.temp_label.raise_()
        self.box3.raise_()
        self.box4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.heart_label.raise_()
        self.o2_label.raise_()
        self.box1.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.seperate_bar.raise_()
        self.seperate_bar_2.raise_()
        self.seperate_bar_3.raise_()
        self.seperate_bar_4.raise_()
        self.seperate_bar_5.raise_()
        self.p_num.raise_()
        self.p_name.raise_()
        self.p_age.raise_()
        self.p_gender.raise_()
        self.p_gard.raise_()
        self.label_21.raise_()
        self.p_gard_2.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.balance_btn_on.raise_()
        self.seperate_bar_6.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_5.raise_()
        self.exit_btn.raise_()
        self.battery_amount.raise_()

        self.retranslateUi(Form)
        self.pushButton_bms.clicked.connect(Form.goBms)
        self.balance_btn_off.clicked.connect(Form.cell_balance_on)
        self.balance_btn_on.clicked.connect(Form.cell_balance_off)
        self.exit_btn.clicked.connect(Form.exit)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.logo_link.setText("")
        self.box5.setText("")
        self.pushButton_bms.setText("")
        self.label.setText("")
        self.label_text.setText(QCoreApplication.translate("Form", u"\ubc30\ud130\ub9ac \uc815\ubcf4", None))
        self.balance_btn_off.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"cell balance", None))
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("Form", u"%", None))
        self.battery_amount.setText(QCoreApplication.translate("Form", u"100", None))
        self.battery_amount_bar.setText("")
        self.box2.setText("")
        self.label_6.setText("")
        self.label_7.setText(QCoreApplication.translate("Form", u"\uccb4\uc628", None))
        self.temp_label.setText(QCoreApplication.translate("Form", u"36.5", None))
        self.box3.setText("")
        self.box4.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText(QCoreApplication.translate("Form", u"\uc2ec\ubc15\uc218", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\uc0b0\uc18c\ud3ec\ud654\ub3c4", None))
        self.heart_label.setText(QCoreApplication.translate("Form", u"120", None))
        self.o2_label.setText(QCoreApplication.translate("Form", u"80", None))
        self.box1.setText("")
        self.label_15.setText(QCoreApplication.translate("Form", u"\ud658\uc790 \uc0c1\uc138 \uc815\ubcf4", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"\ud658\uc790\ubc88\ud638", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"\uc774\ub984", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"\ub098\uc774", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"\uc131\ubcc4", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"\ubcf4\ud638\uc790", None))
        self.seperate_bar.setText("")
        self.seperate_bar_2.setText("")
        self.seperate_bar_3.setText("")
        self.seperate_bar_4.setText("")
        self.seperate_bar_5.setText("")
        self.p_num.setText(QCoreApplication.translate("Form", u"100110", None))
        self.p_name.setText(QCoreApplication.translate("Form", u"\ubb38\uc694\uc131", None))
        self.p_age.setText(QCoreApplication.translate("Form", u"29", None))
        self.p_gender.setText(QCoreApplication.translate("Form", u"\ub0a8", None))
        self.p_gard.setText(QCoreApplication.translate("Form", u"\uac00\ub098\ub2e4", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"\ubcf4\ud638\uc790 \uc5f0\ub77d\ucc98", None))
        self.p_gard_2.setText(QCoreApplication.translate("Form", u"010 - 1234 -5678", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"\uc8fc\uce58\uc758", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"\ub77c\ub9c8\ubc14", None))
        self.balance_btn_on.setText("")
        self.seperate_bar_6.setText("")
        self.box6.setText("")
        self.label_5.setText(QCoreApplication.translate("Form", u"\uc140\ubc38\ub7f0\uc2f1\uc774 \ud544\uc694\ud569\ub2c8\ub2e4", None))
        self.exit_btn.setText("")
    # retranslateUi

