# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUI.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide2.QtWidgets import (QApplication, QLabel, QPushButton, QSizePolicy,
    QWidget,QGraphicsDropShadowEffect,QGraphicsOpacityEffect)
import myres_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1280, 720)
        Form.setStyleSheet(u"background-color: rgb(246, 247, 248);")
        self.logo_link = QLabel(Form)
        self.logo_link.setObjectName(u"logo_link")
        self.logo_link.setGeometry(QRect(579, 60, 148, 50))
        self.logo_link.setStyleSheet(u"border-image: url(:/logo/img/logo_little.png);")
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(88, 55, 95, 54))
        self.label_3.setStyleSheet(u"border-image: url(:/icons/img/battery.png);\n"
"background-color : rgb(246, 247, 248);")
        self.battery_amount = QLabel(Form)
        self.battery_amount.setObjectName(u"battery_amount")
        self.battery_amount.setGeometry(QRect(210, 53, 101, 61))
        font = QFont()
        font.setFamilies([u"Noto Sans KR"])
        font.setPointSize(22)
        font.setBold(True)
        self.battery_amount.setFont(font)
        self.battery_amount.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(246, 247, 248);")
        self.battery_amount_bar = QLabel(Form)
        self.battery_amount_bar.setObjectName(u"battery_amount_bar")
        self.battery_amount_bar.setGeometry(QRect(93, 60, 80, 44))
        self.battery_amount_bar.setStyleSheet(u"background-color: rgb(26, 50, 98);")
        self.box2 = QLabel(Form)
        self.box2.setObjectName(u"box2")
        self.box2.setGeometry(QRect(340, 140, 244, 170))
        self.box2.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(380, 166, 40, 40))
        self.label_6.setStyleSheet(u"border-image: url(:/icons/img/temp_icon_little.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(433, 173, 47, 27))
        font1 = QFont()
        font1.setFamilies([u"Noto Sans KR"])
        font1.setPointSize(16)
        font1.setBold(True)
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.temp_label = QLabel(Form)
        self.temp_label.setObjectName(u"temp_label")
        self.temp_label.setGeometry(QRect(412, 231, 100, 44))
        font2 = QFont()
        font2.setFamilies([u"Noto Sans KR"])
        font2.setPointSize(26)
        font2.setBold(True)
        self.temp_label.setFont(font2)
        self.temp_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.temp_label.setAlignment(Qt.AlignCenter)
        self.box3 = QLabel(Form)
        self.box3.setObjectName(u"box3")
        self.box3.setGeometry(QRect(340, 332, 244, 170))
        self.box3.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.box4 = QLabel(Form)
        self.box4.setObjectName(u"box4")
        self.box4.setGeometry(QRect(340, 524, 244, 170))
        self.box4.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(380, 358, 40, 40))
        self.label_11.setStyleSheet(u"border-image: url(:/icons/img/heart_icon.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_12 = QLabel(Form)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(380, 550, 40, 40))
        self.label_12.setStyleSheet(u"border-image: url(:/icons/img/oxygen-icon.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_13 = QLabel(Form)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(428, 365, 80, 27))
        self.label_13.setFont(font1)
        self.label_13.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_13.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_14 = QLabel(Form)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(428, 557, 134, 27))
        self.label_14.setFont(font1)
        self.label_14.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.label_14.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.heart_label = QLabel(Form)
        self.heart_label.setObjectName(u"heart_label")
        self.heart_label.setGeometry(QRect(412, 414, 100, 44))
        self.heart_label.setFont(font2)
        self.heart_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.heart_label.setAlignment(Qt.AlignCenter)
        self.o2_label = QLabel(Form)
        self.o2_label.setObjectName(u"o2_label")
        self.o2_label.setGeometry(QRect(412, 615, 100, 44))
        self.o2_label.setFont(font2)
        self.o2_label.setStyleSheet(u"color: rgb(26, 50, 98);\n"
"background-color: rgb(255, 255, 255);")
        self.o2_label.setAlignment(Qt.AlignCenter)
        self.box1 = QLabel(Form)
        self.box1.setObjectName(u"box1")
        self.box1.setGeometry(QRect(36, 140, 280, 554))
        self.box1.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.label_15 = QLabel(Form)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(82, 162, 188, 35))
        self.label_15.setFont(font1)
        self.label_15.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(26, 50, 98);")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(Form)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(80, 252, 80, 20))
        font3 = QFont()
        font3.setFamilies([u"Noto Sans KR"])
        font3.setPointSize(14)
        font3.setBold(False)
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_17 = QLabel(Form)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(80, 310, 80, 20))
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_18 = QLabel(Form)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(80, 368, 80, 20))
        self.label_18.setFont(font3)
        self.label_18.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(80, 426, 80, 20))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_20 = QLabel(Form)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(80, 484, 80, 20))
        self.label_20.setFont(font3)
        self.label_20.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.seperate_bar = QLabel(Form)
        self.seperate_bar.setObjectName(u"seperate_bar")
        self.seperate_bar.setGeometry(QRect(160, 252, 2, 21))
        self.seperate_bar.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_2 = QLabel(Form)
        self.seperate_bar_2.setObjectName(u"seperate_bar_2")
        self.seperate_bar_2.setGeometry(QRect(160, 310, 2, 21))
        self.seperate_bar_2.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_3 = QLabel(Form)
        self.seperate_bar_3.setObjectName(u"seperate_bar_3")
        self.seperate_bar_3.setGeometry(QRect(160, 368, 2, 21))
        self.seperate_bar_3.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_4 = QLabel(Form)
        self.seperate_bar_4.setObjectName(u"seperate_bar_4")
        self.seperate_bar_4.setGeometry(QRect(160, 426, 2, 21))
        self.seperate_bar_4.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_5 = QLabel(Form)
        self.seperate_bar_5.setObjectName(u"seperate_bar_5")
        self.seperate_bar_5.setGeometry(QRect(160, 484, 2, 21))
        self.seperate_bar_5.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.p_num = QLabel(Form)
        self.p_num.setObjectName(u"p_num")
        self.p_num.setGeometry(QRect(190, 254, 91, 20))
        font4 = QFont()
        font4.setFamilies([u"Noto Sans KR"])
        font4.setPointSize(14)
        font4.setBold(True)
        self.p_num.setFont(font4)
        self.p_num.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_name = QLabel(Form)
        self.p_name.setObjectName(u"p_name")
        self.p_name.setGeometry(QRect(190, 312, 91, 20))
        self.p_name.setFont(font4)
        self.p_name.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_age = QLabel(Form)
        self.p_age.setObjectName(u"p_age")
        self.p_age.setGeometry(QRect(190, 370, 91, 20))
        self.p_age.setFont(font4)
        self.p_age.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gender = QLabel(Form)
        self.p_gender.setObjectName(u"p_gender")
        self.p_gender.setGeometry(QRect(190, 428, 91, 20))
        self.p_gender.setFont(font4)
        self.p_gender.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard = QLabel(Form)
        self.p_gard.setObjectName(u"p_gard")
        self.p_gard.setGeometry(QRect(190, 486, 91, 20))
        self.p_gard.setFont(font4)
        self.p_gard.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_21 = QLabel(Form)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(81, 602, 141, 20))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard_2 = QLabel(Form)
        self.p_gard_2.setObjectName(u"p_gard_2")
        self.p_gard_2.setGeometry(QRect(90, 632, 180, 31))
        font5 = QFont()
        font5.setFamilies([u"Noto Sans KR"])
        font5.setPointSize(15)
        font5.setBold(True)
        self.p_gard_2.setFont(font5)
        self.p_gard_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.p_gard_2.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(Form)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(80, 542, 61, 20))
        self.label_22.setFont(font3)
        self.label_22.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_23 = QLabel(Form)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(190, 544, 81, 31))
        self.label_23.setFont(font4)
        self.label_23.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.seperate_bar_6 = QLabel(Form)
        self.seperate_bar_6.setObjectName(u"seperate_bar_6")
        self.seperate_bar_6.setGeometry(QRect(160, 542, 2, 21))
        self.seperate_bar_6.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.exit_btn = QPushButton(Form)
        self.exit_btn.setObjectName(u"exit_btn")
        self.exit_btn.setGeometry(QRect(1197, 60, 36, 44))
        self.exit_btn.setStyleSheet(u"border-image: url(:/icons/img/exit_icon.png);")
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(123, 67, 21, 31))
        self.label_8.setStyleSheet(u"background-color: rgba(26, 50, 99,0);\n"
"border-image: url(:/icons/img/volt_icon.png);")
        self.box5 = QLabel(Form)
        self.box5.setObjectName(u"box5")
        self.box5.setGeometry(QRect(610, 140, 621, 554))
        self.box5.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius : 20px;")
        self.seperate_bar_7 = QLabel(Form)
        self.seperate_bar_7.setObjectName(u"seperate_bar_7")
        self.seperate_bar_7.setGeometry(QRect(620, 325, 600, 2))
        self.seperate_bar_7.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.seperate_bar_8 = QLabel(Form)
        self.seperate_bar_8.setObjectName(u"seperate_bar_8")
        self.seperate_bar_8.setGeometry(QRect(620, 510, 600, 2))
        self.seperate_bar_8.setStyleSheet(u"background-color: rgb(213, 213, 213);")
        self.bms_btn = QPushButton(Form)
        self.bms_btn.setObjectName(u"bms_btn")
        self.bms_btn.setGeometry(QRect(80, 50, 181, 71))
        self.bms_btn.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")

        self.shadow1 = QGraphicsDropShadowEffect()
        self.shadow1.setColor(QColor(212, 212, 212))
        self.shadow1.setBlurRadius(15)
        self.shadow1.setOffset(4)

        self.shadow2 = QGraphicsDropShadowEffect()
        self.shadow2.setColor(QColor(212, 212, 212))
        self.shadow2.setBlurRadius(15)
        self.shadow2.setOffset(4)

        self.shadow3 = QGraphicsDropShadowEffect()
        self.shadow3.setColor(QColor(212, 212, 212))
        self.shadow3.setBlurRadius(15)
        self.shadow3.setOffset(4)

        self.shadow4 = QGraphicsDropShadowEffect()
        self.shadow4.setColor(QColor(212, 212, 212))
        self.shadow4.setBlurRadius(15)
        self.shadow4.setOffset(4)

        self.shadow5 = QGraphicsDropShadowEffect()
        self.shadow5.setColor(QColor(212, 212, 212))
        self.shadow5.setBlurRadius(15)
        self.shadow5.setOffset(4)


        self.box1.setGraphicsEffect(self.shadow1)
        self.box2.setGraphicsEffect(self.shadow2)
        self.box3.setGraphicsEffect(self.shadow3)
        self.box4.setGraphicsEffect(self.shadow4)
        self.box5.setGraphicsEffect(self.shadow5)

        opacity_effect = QGraphicsOpacityEffect(self.bms_btn)
        opacity_effect.setOpacity(0)
        self.bms_btn.setGraphicsEffect(opacity_effect)

        self.logo_link.raise_()
        self.label_3.raise_()
        self.battery_amount_bar.raise_()
        self.box2.raise_()
        self.label_7.raise_()
        self.temp_label.raise_()
        self.box3.raise_()
        self.box4.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.heart_label.raise_()
        self.o2_label.raise_()
        self.box1.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.seperate_bar.raise_()
        self.seperate_bar_2.raise_()
        self.seperate_bar_3.raise_()
        self.seperate_bar_4.raise_()
        self.seperate_bar_5.raise_()
        self.p_num.raise_()
        self.p_name.raise_()
        self.p_age.raise_()
        self.p_gender.raise_()
        self.p_gard.raise_()
        self.label_21.raise_()
        self.p_gard_2.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.seperate_bar_6.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.exit_btn.raise_()
        self.battery_amount.raise_()
        self.label_8.raise_()
        self.box5.raise_()
        self.seperate_bar_7.raise_()
        self.seperate_bar_8.raise_()
        self.bms_btn.raise_()

        self.retranslateUi(Form)
        self.exit_btn.clicked.connect(Form.exit)
        self.bms_btn.clicked.connect(Form.goBms)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.logo_link.setText("")
        self.label_3.setText("")
        self.battery_amount.setText(QCoreApplication.translate("Form", u"100", None))
        self.battery_amount_bar.setText("")
        self.box2.setText("")
        self.label_6.setText("")
        self.label_7.setText(QCoreApplication.translate("Form", u"\uccb4\uc628", None))
        self.temp_label.setText(QCoreApplication.translate("Form", u"36.5", None))
        self.box3.setText("")
        self.box4.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText(QCoreApplication.translate("Form", u"\uc2ec\ubc15\uc218", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\uc0b0\uc18c\ud3ec\ud654\ub3c4", None))
        self.heart_label.setText(QCoreApplication.translate("Form", u"120", None))
        self.o2_label.setText(QCoreApplication.translate("Form", u"80", None))
        self.box1.setText("")
        self.label_15.setText(QCoreApplication.translate("Form", u"\ud658\uc790 \uc0c1\uc138 \uc815\ubcf4", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"\ud658\uc790\ubc88\ud638", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"\uc774\ub984", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"\ub098\uc774", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"\uc131\ubcc4", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"\ubcf4\ud638\uc790", None))
        self.seperate_bar.setText("")
        self.seperate_bar_2.setText("")
        self.seperate_bar_3.setText("")
        self.seperate_bar_4.setText("")
        self.seperate_bar_5.setText("")
        self.p_num.setText(QCoreApplication.translate("Form", u"100110", None))
        self.p_name.setText(QCoreApplication.translate("Form", u"\ubb38\uc694\uc131", None))
        self.p_age.setText(QCoreApplication.translate("Form", u"29", None))
        self.p_gender.setText(QCoreApplication.translate("Form", u"\ub0a8", None))
        self.p_gard.setText(QCoreApplication.translate("Form", u"\uac00\ub098\ub2e4", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"\ubcf4\ud638\uc790 \uc5f0\ub77d\ucc98", None))
        self.p_gard_2.setText(QCoreApplication.translate("Form", u"010 - 1234 -5678", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"\uc8fc\uce58\uc758", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"\ub77c\ub9c8\ubc14", None))
        self.seperate_bar_6.setText("")
        self.exit_btn.setText("")
        self.label_8.setText("")
        self.box5.setText("")
        self.seperate_bar_7.setText("")
        self.seperate_bar_8.setText("")
        self.bms_btn.setText("")
    # retranslateUi

