# Generated by Django 3.2.16 on 2022-11-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField()),
                ('max_voltage', models.FloatField()),
            ],
            options={
                'db_table': 'battery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('is_charge', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.patient')),
            ],
            options={
                'db_table': 'bms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BmsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('bms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.bms')),
            ],
            options={
                'db_table': 'bms_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('amount', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.battery')),
            ],
            options={
                'db_table': 'battery_status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='bms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.bms'),
        ),
    ]
