# Generated by Django 3.2.16 on 2022-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField()),
                ('max_voltage', models.IntegerField()),
            ],
            options={
                'db_table': 'battery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatteryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('now', models.DateTimeField()),
            ],
            options={
                'db_table': 'battery_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('control', models.IntegerField()),
                ('is_charge', models.BooleanField()),
            ],
            options={
                'db_table': 'bms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BmsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('bms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.bms')),
            ],
            options={
                'db_table': 'bms_status',
                'managed': True,
            },
        ),
    ]
