# Generated by Django 3.2.16 on 2022-10-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0001_initial'),
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wards.patient'),
        ),
        migrations.AddField(
            model_name='batterystatus',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.battery'),
        ),
        migrations.AddField(
            model_name='battery',
            name='bms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.bms'),
        ),
    ]
