# Generated by Django 3.2.16 on 2022-11-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_batterystatusexcel_batterystatusnow_bmsstatusexcel_bmsstatusnow'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmsDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_t', models.IntegerField()),
                ('max_t', models.IntegerField()),
                ('now', models.DateTimeField()),
                ('bms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.bms')),
            ],
            options={
                'db_table': 'bms_day',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BatteryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_v', models.FloatField()),
                ('max_v', models.FloatField()),
                ('now', models.DateTimeField()),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batteries.battery')),
            ],
            options={
                'db_table': 'battery_day',
                'managed': True,
            },
        ),
    ]
