# Generated by Django 3.2.16 on 2022-11-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_alter_bmsstatus_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='max_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='batterystatus',
            name='voltage',
            field=models.FloatField(),
        ),
    ]
