# Generated by Django 3.2.16 on 2022-11-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_batteryday_bmsday'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmsBatteryDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('voltage1', models.FloatField()),
                ('voltage2', models.FloatField()),
            ],
            options={
                'db_table': 'bms_battery_default',
                'managed': True,
            },
        ),
    ]
